GITHUB_OWNER="ilyongnoh-ux"
GITHUB_REPO="https://github.com/ilyongnoh-ux/kfit-auth-test/"          # 권한DB repo
GITHUB_TOKEN="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"
GITHUB_ENTITLEMENTS_PATH="auth/entitlements.json"

# EXE 배포 repo (릴리즈 자산)
DOWNLOAD_OWNER="ilyongnoh-ux"
DOWNLOAD_REPO="KFITER_RELEASES_REPO"
DOWNLOAD_ASSET_NAME="KFITER_Setup.exe"
